### ISSUE TITLE
cannot use `frontMatter` as the `name` option

### ISSUE THREAD

**Issue by xarthurx** [remcohaszing/remark-mdx-frontmatter#12]
Hello, when using this plugin, I cannot get the content of frontmatter with the default setup.

However, if I do:
```
remarkPlugins: [remarkFrontmatter, [remarkMdxFrontmatter, {name: 'matter'}]]
```
I can get the content by `file.matter`. the custom name can be anything except for `frontMatter` (I'll get a `undefined` object)

I think this might be a bug.

See discussion here: https://stackoverflow.com/a/76962139/5737534

**Comment by remcohaszing** [comment]
I don’t understand what you’re trying to do and what’s not working. Can you create a minimal runnable example to demonstrate the problem? Or better: Could you create a pull request with a failing test case?

**Comment by xarthurx** [comment]
I'm trying to get the content of the frontmatter.
I can only get it by rename the `name` to a keyword that is not `frontmatter` (can be `matter`, `dog`, `cat`, etc.)

**Comment by remcohaszing** [comment]
Let me help you formulate the problem:

````md
Given the following script:

```js
import { compile } from '@mdx-js/mdx'
import remarkFrontmatter from 'remark-frontmatter'
import remarkMdxFrontmatter from 'remark-mdx-frontmatter'

const mdx = `---
foo: bar
---

Some content
`

const file = await compile(mdx, {
  remarkPlugins: [
    remarkFrontmatter,
    remarkMdxFrontmatter
  ]
})

console.log(String(file))
```

I expected the following result:

```js

```

But instead I got this:

```js

```

I used the following package versions:

- `@mdx-js/mdx`:
- `remark-frontmatter`:
- `remark-mdx-frontmatter`:
````
