### ISSUE TITLE
Usage example with Next.js app-directory

### ISSUE THREAD

**Issue by tim-hilt** [remcohaszing/remark-mdx-frontmatter#13]
Next.js' documentation explicitly mentions `remark-frontmatter` [on their page to set up mdx-support in Next.js](https://nextjs.org/docs/app/building-your-application/configuring/mdx#frontmatter), but they aren't explaining how the generated exports can be used.

I'm not too deep into how remark-plugins work. Do you now how it works? If so, can it be explained simply?

If this is something you would be interested in, I could make two PRs to enhance both this repositories README.md and the Next.js docs. This wouldn't only help me out with what I currently want to do, but also potentially advertise this plugin to a bigger audience.

**Comment by remcohaszing** [comment]
I don't really understand what needs to be explained. The generated export can be used like any other export.

If you would like to learn more about plugins, unified has [some guides](https://unifiedjs.com/learn/). You can also look at existing plugins. I also recommend using [AST explorer](https://astexplorer.net/) to see what code generates what AST.

I'm not really interested in adding platform specific instructions to the readme, but it would be great if Next.js links to this plugin.
