### ISSUE TITLE
Expose all data from frontmatter on `vfile.matter`

### ISSUE THREAD

**Issue by wooorm** [remcohaszing/remark-mdx-frontmatter#2]
Similar to [`vfile-matter`](https://github.com/vfile/vfile-matter).
This allows manual overrides per file for `rehype-meta` (and perhaps other future plugins that support inline configuration)

**Comment by remcohaszing** [comment]
I believe this plugin should focus on exposing frontmatter metadata as exports, not on exposing it to other unified plugins. If this is something we’d want, I think the parsing should be moved into [`remark-frontmatter`](https://github.com/remarkjs/remark-frontmatter) instead. The `matter` options will have to take a `parse` property, which is a function which converts the string data to a value.

```js
{ type: 'yaml', marker: '-', parse: yaml.load }
{ type: 'toml', marker: '+', parse: toml.parse }
```

I also believe this plugin could then be deprecated in favor of `recma-expose-meta`.

**Comment by wooorm** [comment]
Reason for not including js-yaml or so in `remark-frontmatter` is that it would increate the bundle size a ton. While sometimes useful, I think it should be possible to parse frontmatter in markdown, without having to include a full YAML/TOML/etc parser

**Comment by remcohaszing** [comment]
I’m closing this issue, because I don’t think this plugin is the right place.
