### ISSUE TITLE
remark-frontmatter 2.0?

### ISSUE THREAD

**Issue by msakrejda** [remcohaszing/remark-mdx-frontmatter#3]
Hello,

I'm trying to get remark-mdx-frontmatter to work with [vite-plugin-mdx](https://github.com/brillout/vite-plugin-mdx/pull/31), but the latter only seems to support remark-frontmatter 2, and remark-mdx-frontmatter only seems to support 3.0 according to its dev deps in package.json. I tried with [a fork of the example](https://github.com/uhoh-itsmaciek/vite-plugin-mdx/pull/1) from vite-plugin-mdx, but on 3.0 remark-frontmatter still ignores frontmatter and it shows up as part of the MDX React component rendering, and on 2.0 remark-frontmatter appears to parse and strip the frontmatter directly, but it's not actually made available in the module exports by react-mdx-frontmatter.

Any ideas?

**Comment by remcohaszing** [comment]
Thanks for reporting this. The situation around mdx is a bit confusing now, so here’s a small explanation of the situation:

- The xdm team has been working towards version 2.0.0
- There were some disagreements within the xdm team. This resulted in a new (IMO better) implementation of xdm: [xdm](https://github.com/wooorm/xdm)
- The issues in the mdx team have been resolved and they are now working hard to backport the features of xdm into mdx.

This package is compatible with xdm, and possibly `@mdx-js/mdx@next`. I should be fully compatible once mdx 2.0.0 is released.

I noticed the linked example uses `@mdx-js/mdx@^1.6.22`, but the vite plugin uses `@mdx-js/mdx@^2.0.0-next.9`. I recommend upgrading mdx in the example.

If that doesn’t work all I can say is: please be patient until mdx 2 is stable.

**Comment by uhoh-itsmaciek** [comment]
Yes, thank you!

I tried upgrading the example to 2.0.0-next.9, but no dice. What's the best way to track mdx 2?

Also, could downgrading remark-mdx-frontmatter help here, in the short term? If so, any ideas on what older versions to try?
