### ISSUE TITLE
Export `options.name` when there is no YAML

### ISSUE THREAD

**Issue by wooorm** [remcohaszing/remark-mdx-frontmatter#5]
Using this plugin with a name lead me to believe that there would always be such an identifier exported.
I think it would make sense to either use `undefined` or `{}` as the value when there is no YAML frontmatter in files in such cases

**Comment by remcohaszing** [comment]
That makes sense. I think the value should be `undefined` then.

**Comment by remcohaszing** [comment]
This was just added in version 2 :rocket:
