### ISSUE TITLE
Named exports and HMR

### ISSUE THREAD

**Issue by guoyunhe** [remcohaszing/remark-mdx-frontmatter#9]
I am using Vite + MDX with this plugin. It works fine. But refresh is slow. Not like HMR but a page refresh.

Then I found this https://github.com/vitejs/vite/discussions/4583

Frontmatter add named exports to MDX:

```jsx
export const title = 'My Title';

export default function MDX() { ... }
```

The named export `title` will break HMR, meaning that whenever I modify a MDX file, the page will refresh instead of hot module replacement.

To solve the issue, I think it is better to generate code without named exports:

```jsx
function MDX() { ... }

MDX.title = 'My Title';

export default MDX;
```

**Comment by remcohaszing** [comment]
Thanks for reporting this!

I’m personally not a fan of this solution. I think it’s a bug in the HMR library, not this package.

Have you tried using a name instead? That would output something like:

```js
export const frontmatter = { title: 'My Title' };

export default function MDX() { ... }
```

So this still outputs an exported variable, but it only happens once, not for every key.

Also [this](https://github.com/vitejs/vite/discussions/4583#discussioncomment-2736454) might help, but I need to wait for an answer to be sure.

**Comment by remcohaszing** [comment]
I’m going to close this as a _won’t fix_, because it’s a bug in the HMR library, not this one.

One solution you could try is to create a recma plugin for MDX which removes all exports, then assigns all exported variables to `MDXContent`.

In:

```js
export const foo = 'asd'

export function bar() {}

export default function MDXContent() {}
```

Out:

```js
const foo = 'asd'

function bar() {}

export default function MDXContent() {}

MDXContent.foo = foo
MDXContent.bar = bar
```
